// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph2.callrecords.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph2.callrecords.models.extensions.SingletonEntity1;
import com.microsoft.graph.requests.extensions.TestTypeRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Singleton Entity1Request.
 */
public class SingletonEntity1Request extends BaseRequest<SingletonEntity1> {
	
    /**
     * The request for the SingletonEntity1
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public SingletonEntity1Request(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, SingletonEntity1.class);
    }

    /**
     * Gets the SingletonEntity1 from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.Future<? super SingletonEntity1> futureGet() {
        return futureSend(HttpMethod.GET, null);
    }

    /**
     * Gets the SingletonEntity1 from the service
     *
     * @return the SingletonEntity1 from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public SingletonEntity1 get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.Future<? super SingletonEntity1> futureDelete() {
        return futureSend(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public SingletonEntity1 delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this SingletonEntity1 with a source
     *
     * @param sourceSingletonEntity1 the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.Future<? super SingletonEntity1> futurePatch(@Nonnull final SingletonEntity1 sourceSingletonEntity1) {
        return futureSend(HttpMethod.PATCH, sourceSingletonEntity1);
    }

    /**
     * Patches this SingletonEntity1 with a source
     *
     * @param sourceSingletonEntity1 the source object with updates
     * @return the updated SingletonEntity1
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public SingletonEntity1 patch(@Nonnull final SingletonEntity1 sourceSingletonEntity1) throws ClientException {
        return send(HttpMethod.PATCH, sourceSingletonEntity1);
    }

    /**
     * Creates a SingletonEntity1 with a new object
     *
     * @param newSingletonEntity1 the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.Future<? super SingletonEntity1> futurePost(@Nonnull final SingletonEntity1 newSingletonEntity1) {
        return futureSend(HttpMethod.POST, newSingletonEntity1);
    }

    /**
     * Creates a SingletonEntity1 with a new object
     *
     * @param newSingletonEntity1 the new object to create
     * @return the created SingletonEntity1
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public SingletonEntity1 post(@Nonnull final SingletonEntity1 newSingletonEntity1) throws ClientException {
        return send(HttpMethod.POST, newSingletonEntity1);
    }

    /**
     * Creates a SingletonEntity1 with a new object
     *
     * @param newSingletonEntity1 the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.Future<? super SingletonEntity1> futurePut(@Nonnull final SingletonEntity1 newSingletonEntity1) {
        return futureSend(HttpMethod.PUT, newSingletonEntity1);
    }

    /**
     * Creates a SingletonEntity1 with a new object
     *
     * @param newSingletonEntity1 the object to create/update
     * @return the created SingletonEntity1
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public SingletonEntity1 put(@Nonnull final SingletonEntity1 newSingletonEntity1) throws ClientException {
        return send(HttpMethod.PUT, newSingletonEntity1);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public SingletonEntity1Request select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public SingletonEntity1Request expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

