// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EnumType.cs.tt


namespace Microsoft.Graph.SecurityNamespace
{
    using System.Text.Json.Serialization;

    /// <summary>
    /// The enum AlertClassification.
    /// </summary>
    [JsonConverter(typeof(JsonStringEnumConverter))]
    public enum AlertClassification
    {
    
        /// <summary>
        /// Unknown
        /// </summary>
        Unknown = 0,
	
        /// <summary>
        /// False Positive
        /// </summary>
        FalsePositive = 10,
	
        /// <summary>
        /// True Positive
        /// </summary>
        TruePositive = 20,
	
        /// <summary>
        /// Informational Expected Activity
        /// </summary>
        InformationalExpectedActivity = 30,
	
        /// <summary>
        /// Unknown Future Value
        /// </summary>
        UnknownFutureValue = 39,
	
    }
}
