// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;
import com.microsoft.graph.models.extensions.SingletonEntity2;

import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.http.IHttpRequest;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Singleton Entity2Request.
 */
public interface ISingletonEntity2Request extends IHttpRequest {

    /**
     * Gets the SingletonEntity2 from the service
     *
     * @param callback the callback to be called after success or failure
     */
    void get(final ICallback<SingletonEntity2> callback);

    /**
     * Gets the SingletonEntity2 from the service
     *
     * @return the SingletonEntity2 from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    SingletonEntity2 get() throws ClientException;

    /**
     * Delete this item from the service
     *
     * @param callback the callback when the deletion action has completed
     */
    void delete(final ICallback<SingletonEntity2> callback);

    /**
     * Delete this item from the service
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    void delete() throws ClientException;

    /**
     * Patches this SingletonEntity2 with a source
     *
     * @param sourceSingletonEntity2 the source object with updates
     * @param callback the callback to be called after success or failure
     */
    void patch(final SingletonEntity2 sourceSingletonEntity2, final ICallback<SingletonEntity2> callback);

    /**
     * Patches this SingletonEntity2 with a source
     *
     * @param sourceSingletonEntity2 the source object with updates
     * @return the updated SingletonEntity2
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    SingletonEntity2 patch(final SingletonEntity2 sourceSingletonEntity2) throws ClientException;

    /**
     * Posts a SingletonEntity2 with a new object
     *
     * @param newSingletonEntity2 the new object to create
     * @param callback the callback to be called after success or failure
     */
    void post(final SingletonEntity2 newSingletonEntity2, final ICallback<SingletonEntity2> callback);

    /**
     * Posts a SingletonEntity2 with a new object
     *
     * @param newSingletonEntity2 the new object to create
     * @return the created SingletonEntity2
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    SingletonEntity2 post(final SingletonEntity2 newSingletonEntity2) throws ClientException;

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    ISingletonEntity2Request select(final String value);

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    ISingletonEntity2Request expand(final String value);

}

