// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.DerivedComplexTypeRequest;
import com.microsoft.graph.models.extensions.ResponseObject;
import java.util.Arrays;
import java.util.EnumSet;

import com.microsoft.graph.http.BaseCollectionPage;
import com.microsoft.graph.requests.extensions.TestTypeQueryCollectionRequestBuilder;
import com.microsoft.graph.requests.extensions.TestTypeQueryCollectionPage;
import com.microsoft.graph.requests.extensions.TestTypeQueryCollectionResponse;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Test Type Query Collection Page.
 */
public class TestTypeQueryCollectionPage extends BaseCollectionPage<ResponseObject, TestTypeQueryCollectionRequestBuilder> {

    /**
     * A collection page for ResponseObject.
     *
     * @param response The serialized TestTypeQueryCollectionResponse from the service
     * @param builder The request builder for the next collection page
     */
    public TestTypeQueryCollectionPage(final TestTypeQueryCollectionResponse response, final TestTypeQueryCollectionRequestBuilder builder) {
       super(response, builder);
    }

	/**
     * Creates the collection page for TestTypeQuery
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public TestTypeQueryCollectionPage(final java.util.List<ResponseObject> pageContents, final TestTypeQueryCollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
