version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
  groups:
    MSTestFramework:
      patterns:
        - "Microsoft.NET.Test*"
        - "MSTest.*"
    NUnitTestFramework:
      patterns:
        - "NUnit*"

  open-pull-requests-limit: 10
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 1
