steps:
- checkout: self
  displayName: checkout generator
  fetchDepth: 1
  submodules: recursive
  persistCredentials: true

- task: DotNetCoreCLI@2
  displayName: 'Build Typewriter'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/MSGraph-SDK-Code-Generator/src/Typewriter/Typewriter.csproj'
    arguments: '--configuration $(buildConfiguration)'