parameters:
  - name: repoName
    type: string

steps:
  - pwsh: "$(scriptsDirectory)/copy-ccs-typescript-sdk-models.ps1"
    displayName: "Update models"
    env:
      OutputFullPath: $(kiotaDirectory)
      RepoModelsDir: $(Build.SourcesDirectory)/${{ parameters.repoName }}/packages/
