parameters:
  - name: repoName
    type: string

steps:
  - pwsh: '$(scriptsDirectory)/copy-ccs-typescript-sdk-models.ps1 -sourceDirectory "$(kiotaDirectory)/output/" -targetDirectory "$(Build.SourcesDirectory)/${{ parameters.repoName }}/packages/"'
    displayName: "Update models"
