steps:
- template: set-up-for-generation.yml

- checkout: msgraph-sdk-dotnet
  displayName: checkout dotnet
  fetchDepth: 1
  persistCredentials: true

- pwsh: '$(scriptsDirectory)/run-typewriter.ps1'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputPath: $(outputDotNetV1)
    CleanMetadataFile: $(cleanMetadataFileV1)
    TypewriterExecutable: $(typewriterExecutable)
    TypewriterDirectory: $(typewriterDirectory)
    Language: 'CSharp'
  displayName: 'Run Typewriter for CSharp V1'

- pwsh: '$(scriptsDirectory)/create-branch.ps1'
  displayName: 'Create a branch'
  env:
    RepoDirectory: $(Build.SourcesDirectory)/msgraph-sdk-dotnet
    BranchName: $(v1Branch)

- pwsh: '$(scriptsDirectory)/copy-dotnet-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/$(outputDotNetV1)
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-sdk-dotnet/src/Microsoft.Graph/Generated/

- template: dotnet-v1-validation.yml

- pwsh: '$(scriptsDirectory)/git-push-files.ps1'
  displayName: 'Git: push generated files'
  env:
    BranchName: $(v1Branch)
  workingDirectory: '$(Build.SourcesDirectory)/msgraph-sdk-dotnet'
