steps:
- pwsh: '$(scriptsDirectory)/copy-dotnet-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/output${{ parameters.language }}${{ parameters.version }}
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-beta-sdk-dotnet/src/Microsoft.Graph/Generated/

- task: DotNetCoreCLI@2
  displayName: 'Build Microsoft.Graph.Beta.dll'
  inputs:
    command: 'build'
    projects: msgraph-beta-sdk-dotnet/**/*.csproj
    arguments: '--configuration $(buildConfiguration)'

- pwsh: |
    $allGeneratedDlls = Get-ChildItem -Include Microsoft.Graph.Beta.dll -Recurse
    $dotNetFrameworkDll = $allGeneratedDlls | Where-Object { $_.FullName.Contains("net461") } | Select-Object -First 1 # TODO hardcoded .NET version
    $dllPath = $dotNetFrameworkDll.FullName

    & ./scripts/generateTypeSummary.ps1 -dllPath $dllPath -outputPath $env:BUILD_SOURCESDIRECTORY/msgraph-beta-sdk-dotnet/typeSummary.txt
  displayName: 'Generate type summary'
  workingDirectory: '$(Build.SourcesDirectory)/msgraph-beta-sdk-dotnet'