steps:
- pwsh: |
    # Example directories are:
    # src/Model (types in microsoft.graph namespace)
    # src/CallRecords/Model (types in microsoft.graph.callRecords namespace)
    Get-ChildItem ./src/ -Exclude Beta,Core,Exception,Http -Directory | Remove-Item -Force -Recurse
    Write-Host "Removed the existing generated files in the repo at $modelDir." -ForegroundColor Green

  displayName: 'Remove generated files from the repo'
  workingDirectory: $(Build.SourcesDirectory)/msgraph-sdk-php 

- pwsh: '$(scriptsDirectory)/copy-php-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPathV1: $(typewriterDirectory)/output
    OutputFullPathBeta: $(typewriterDirectory)/output
    RepoModelsDirV1: $(Build.SourcesDirectory)/msgraph-sdk-php/src/
    RepoModelsDirBeta: $(Build.SourcesDirectory)/msgraph-sdk-php/src/Beta

# TODO run PHP tests