steps:
- template: set-up-for-generation.yml

- checkout: msgraph-typescript-typings
  displayName: checkout typescript
  fetchDepth: 1
  persistCredentials: true

- pwsh: '$(scriptsDirectory)/run-typewriter.ps1'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputPath: $(outputTypeScriptV1)
    CleanMetadataFile: $(cleanMetadataFileV1)
    TypewriterExecutable: $(typewriterExecutable)
    TypewriterDirectory: $(typewriterDirectory)
    Language: 'TypeScript'
  displayName: 'Run Typewriter for TypeScript V1'

- pwsh: '$(scriptsDirectory)/run-typewriter.ps1'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputPath: $(outputTypeScriptBeta)
    CleanMetadataFile: $(cleanMetadataFileBeta)
    TypewriterExecutable: $(typewriterExecutable)
    TypewriterDirectory: $(typewriterDirectory)
    Language: 'TypeScript'
    Endpoint: 'beta'
  displayName: 'Run Typewriter for TypeScript Beta'

# copy v1 generated files
- pwsh: '$(scriptsDirectory)/create-branch.ps1'
  displayName: 'Create a branch'
  env:
    RepoDirectory: $(Build.SourcesDirectory)/msgraph-typescript-typings
    BranchName: $(v1Branch)

- pwsh: '$(scriptsDirectory)/copy-typescript-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/$(outputTypeScriptV1)
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-typescript-typings/

- pwsh: '$(scriptsDirectory)/git-push-files.ps1'
  displayName: 'Git: push generated files'
  env:
    BranchName: $(v1Branch)
  workingDirectory: '$(Build.SourcesDirectory)/msgraph-typescript-typings'

# switch to beta branch
- pwsh: |
    git fetch
    git checkout beta
  displayName: 'Switch to beta branch'
  workingDirectory: '$(Build.SourcesDirectory)/msgraph-typescript-typings'

# copy beta generated files
- pwsh: '$(scriptsDirectory)/create-branch.ps1'
  displayName: 'Create a branch'
  env:
    RepoDirectory: $(Build.SourcesDirectory)/msgraph-typescript-typings
    BranchName: $(typeScriptBetaBranch)

- pwsh: '$(scriptsDirectory)/copy-typescript-models.ps1'
  displayName: 'Update models'
  env:
    BuildConfiguration: $(buildConfiguration)
    OutputFullPath: $(typewriterDirectory)/$(outputTypeScriptBeta)
    RepoModelsDir: $(Build.SourcesDirectory)/msgraph-typescript-typings/

- pwsh: '$(scriptsDirectory)/git-push-files.ps1'
  displayName: 'Git: push generated files'
  env:
    BranchName: $(typeScriptBetaBranch)
  workingDirectory: '$(Build.SourcesDirectory)/msgraph-typescript-typings'