parameters:
- name: 'version'
  type: string
  default: "8.x"

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK'
  inputs:
    packageType: sdk
    version: ${{ parameters.version }}
    installationPath: $(Agent.ToolsDirectory)/dotnet
