// Template Source: BaseEntityRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.models.EmptyEntityTypeWithBaseType;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequest;
import com.microsoft.graph.http.HttpMethod;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Empty Entity Type With Base Type Request.
 */
public class EmptyEntityTypeWithBaseTypeRequest extends BaseRequest<EmptyEntityTypeWithBaseType> {
	
    /**
     * The request for the EmptyEntityTypeWithBaseType
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public EmptyEntityTypeWithBaseTypeRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, EmptyEntityTypeWithBaseType.class);
    }

    /**
     * Gets the EmptyEntityTypeWithBaseType from the service
     *
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<EmptyEntityTypeWithBaseType> getAsync() {
        return sendAsync(HttpMethod.GET, null);
    }

    /**
     * Gets the EmptyEntityTypeWithBaseType from the service
     *
     * @return the EmptyEntityTypeWithBaseType from the request
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public EmptyEntityTypeWithBaseType get() throws ClientException {
       return send(HttpMethod.GET, null);
    }

    /**
     * Delete this item from the service
     *
     * @return a future with the deletion result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<EmptyEntityTypeWithBaseType> deleteAsync() {
        return sendAsync(HttpMethod.DELETE, null);
    }

    /**
     * Delete this item from the service
     * @return the resulting response if the service returns anything on deletion
     *
     * @throws ClientException if there was an exception during the delete operation
     */
    @Nullable
    public EmptyEntityTypeWithBaseType delete() throws ClientException {
        return send(HttpMethod.DELETE, null);
    }

    /**
     * Patches this EmptyEntityTypeWithBaseType with a source
     *
     * @param sourceEmptyEntityTypeWithBaseType the source object with updates
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<EmptyEntityTypeWithBaseType> patchAsync(@Nonnull final EmptyEntityTypeWithBaseType sourceEmptyEntityTypeWithBaseType) {
        return sendAsync(HttpMethod.PATCH, sourceEmptyEntityTypeWithBaseType);
    }

    /**
     * Patches this EmptyEntityTypeWithBaseType with a source
     *
     * @param sourceEmptyEntityTypeWithBaseType the source object with updates
     * @return the updated EmptyEntityTypeWithBaseType
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public EmptyEntityTypeWithBaseType patch(@Nonnull final EmptyEntityTypeWithBaseType sourceEmptyEntityTypeWithBaseType) throws ClientException {
        return send(HttpMethod.PATCH, sourceEmptyEntityTypeWithBaseType);
    }

    /**
     * Creates a EmptyEntityTypeWithBaseType with a new object
     *
     * @param newEmptyEntityTypeWithBaseType the new object to create
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<EmptyEntityTypeWithBaseType> postAsync(@Nonnull final EmptyEntityTypeWithBaseType newEmptyEntityTypeWithBaseType) {
        return sendAsync(HttpMethod.POST, newEmptyEntityTypeWithBaseType);
    }

    /**
     * Creates a EmptyEntityTypeWithBaseType with a new object
     *
     * @param newEmptyEntityTypeWithBaseType the new object to create
     * @return the created EmptyEntityTypeWithBaseType
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public EmptyEntityTypeWithBaseType post(@Nonnull final EmptyEntityTypeWithBaseType newEmptyEntityTypeWithBaseType) throws ClientException {
        return send(HttpMethod.POST, newEmptyEntityTypeWithBaseType);
    }

    /**
     * Creates a EmptyEntityTypeWithBaseType with a new object
     *
     * @param newEmptyEntityTypeWithBaseType the object to create/update
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<EmptyEntityTypeWithBaseType> putAsync(@Nonnull final EmptyEntityTypeWithBaseType newEmptyEntityTypeWithBaseType) {
        return sendAsync(HttpMethod.PUT, newEmptyEntityTypeWithBaseType);
    }

    /**
     * Creates a EmptyEntityTypeWithBaseType with a new object
     *
     * @param newEmptyEntityTypeWithBaseType the object to create/update
     * @return the created EmptyEntityTypeWithBaseType
     * @throws ClientException this exception occurs if the request was unable to complete for any reason
     */
    @Nullable
    public EmptyEntityTypeWithBaseType put(@Nonnull final EmptyEntityTypeWithBaseType newEmptyEntityTypeWithBaseType) throws ClientException {
        return send(HttpMethod.PUT, newEmptyEntityTypeWithBaseType);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
     @Nonnull
     public EmptyEntityTypeWithBaseTypeRequest select(@Nonnull final String value) {
         addSelectOption(value);
         return this;
     }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
     @Nonnull
     public EmptyEntityTypeWithBaseTypeRequest expand(@Nonnull final String value) {
         addExpandOption(value);
         return this;
     }

}

