// Template Source: BaseEntityCollectionPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.requests;
import com.microsoft.graph.models.EntityType3;
import com.microsoft.graph.requests.EntityType3CollectionRequestBuilder;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;
import com.microsoft.graph.requests.EntityType3CollectionResponse;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Entity Type3Collection Page.
 * @deprecated entityType3 is deprecated. Please use singletonEntity1.
 */
@Deprecated
public class EntityType3CollectionPage extends BaseCollectionPage<EntityType3, EntityType3CollectionRequestBuilder> {

    /**
     * A collection page for EntityType3
     *
     * @param response the serialized EntityType3CollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public EntityType3CollectionPage(@Nonnull final EntityType3CollectionResponse response, @Nonnull final EntityType3CollectionRequestBuilder builder) {
        super(response, builder);
    }

    /**
     * Creates the collection page for EntityType3
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public EntityType3CollectionPage(@Nonnull final java.util.List<EntityType3> pageContents, @Nullable final EntityType3CollectionRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
