// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityRequest.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Net.Http;
    using System.Threading;
    using System.Linq.Expressions;

    /// <summary>
    /// The type EmptyEntityTypeWithBaseTypeRequest.
    /// </summary>
    public partial class EmptyEntityTypeWithBaseTypeRequest : BaseRequest, IEmptyEntityTypeWithBaseTypeRequest
    {
        /// <summary>
        /// Constructs a new EmptyEntityTypeWithBaseTypeRequest.
        /// </summary>
        /// <param name="requestUrl">The URL for the built request.</param>
        /// <param name="client">The <see cref="IBaseClient"/> for handling requests.</param>
        /// <param name="options">Query and header option name value pairs for the request.</param>
        public EmptyEntityTypeWithBaseTypeRequest(
            string requestUrl,
            IBaseClient client,
            IEnumerable<Option> options)
            : base(requestUrl, client, options)
        {
        }

        /// <summary>
        /// Creates the specified EmptyEntityTypeWithBaseType using POST.
        /// </summary>
        /// <param name="emptyEntityTypeWithBaseTypeToCreate">The EmptyEntityTypeWithBaseType to create.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The created EmptyEntityTypeWithBaseType.</returns>
        public async System.Threading.Tasks.Task<EmptyEntityTypeWithBaseType> CreateAsync(EmptyEntityTypeWithBaseType emptyEntityTypeWithBaseTypeToCreate, CancellationToken cancellationToken = default(CancellationToken))
        {
            this.ContentType = CoreConstants.MimeTypeNames.Application.Json;
            this.Method = HttpMethods.POST;
            var newEntity = await this.SendAsync<EmptyEntityTypeWithBaseType>(emptyEntityTypeWithBaseTypeToCreate, cancellationToken).ConfigureAwait(false);
            this.InitializeCollectionProperties(newEntity);
            return newEntity;
        }

        /// <summary>
        /// Creates the specified EmptyEntityTypeWithBaseType using POST and returns a <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object.
        /// </summary>
        /// <param name="emptyEntityTypeWithBaseTypeToCreate">The EmptyEntityTypeWithBaseType to create.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object of the request.</returns>
        public System.Threading.Tasks.Task<GraphResponse<EmptyEntityTypeWithBaseType>> CreateResponseAsync(EmptyEntityTypeWithBaseType emptyEntityTypeWithBaseTypeToCreate, CancellationToken cancellationToken = default(CancellationToken))
        {
            this.ContentType = CoreConstants.MimeTypeNames.Application.Json;
            this.Method = HttpMethods.POST;
            return this.SendAsyncWithGraphResponse<EmptyEntityTypeWithBaseType>(emptyEntityTypeWithBaseTypeToCreate, cancellationToken);
        }

        /// <summary>
        /// Deletes the specified EmptyEntityTypeWithBaseType.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task to await.</returns>
        public async System.Threading.Tasks.Task DeleteAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.Method = HttpMethods.DELETE;
            await this.SendAsync<EmptyEntityTypeWithBaseType>(null, cancellationToken).ConfigureAwait(false);
        }

        /// <summary>
        /// Deletes the specified EmptyEntityTypeWithBaseType and returns a <see cref="GraphResponse"/> object.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task of <see cref="GraphResponse"/> to await.</returns>
        public System.Threading.Tasks.Task<GraphResponse> DeleteResponseAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.Method = HttpMethods.DELETE;
            return this.SendAsyncWithGraphResponse(null, cancellationToken);
        }

        /// <summary>
        /// Gets the specified EmptyEntityTypeWithBaseType.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The EmptyEntityTypeWithBaseType.</returns>
        public async System.Threading.Tasks.Task<EmptyEntityTypeWithBaseType> GetAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.Method = HttpMethods.GET;
            var retrievedEntity = await this.SendAsync<EmptyEntityTypeWithBaseType>(null, cancellationToken).ConfigureAwait(false);
            this.InitializeCollectionProperties(retrievedEntity);
            return retrievedEntity;
        }

        /// <summary>
        /// Gets the specified EmptyEntityTypeWithBaseType and returns a <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object of the request.</returns>
        public System.Threading.Tasks.Task<GraphResponse<EmptyEntityTypeWithBaseType>> GetResponseAsync(CancellationToken cancellationToken = default(CancellationToken))
        {
            this.Method = HttpMethods.GET;
            return this.SendAsyncWithGraphResponse<EmptyEntityTypeWithBaseType>(null, cancellationToken);
        }

        /// <summary>
        /// Updates the specified EmptyEntityTypeWithBaseType using PATCH.
        /// </summary>
        /// <param name="emptyEntityTypeWithBaseTypeToUpdate">The EmptyEntityTypeWithBaseType to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <exception cref="ClientException">Thrown when an object returned in a response is used for updating an object in Microsoft Graph.</exception>
        /// <returns>The updated EmptyEntityTypeWithBaseType.</returns>
        public async System.Threading.Tasks.Task<EmptyEntityTypeWithBaseType> UpdateAsync(EmptyEntityTypeWithBaseType emptyEntityTypeWithBaseTypeToUpdate, CancellationToken cancellationToken = default(CancellationToken))
        {
            this.ContentType = CoreConstants.MimeTypeNames.Application.Json;
            this.Method = HttpMethods.PATCH;
            var updatedEntity = await this.SendAsync<EmptyEntityTypeWithBaseType>(emptyEntityTypeWithBaseTypeToUpdate, cancellationToken).ConfigureAwait(false);
            this.InitializeCollectionProperties(updatedEntity);
            return updatedEntity;
        }

        /// <summary>
        /// Updates the specified EmptyEntityTypeWithBaseType using PATCH and returns a <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object.
        /// </summary>
        /// <param name="emptyEntityTypeWithBaseTypeToUpdate">The EmptyEntityTypeWithBaseType to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <exception cref="ClientException">Thrown when an object returned in a response is used for updating an object in Microsoft Graph.</exception>
        /// <returns>The <see cref="GraphResponse{EmptyEntityTypeWithBaseType}"/> object of the request.</returns>
        public System.Threading.Tasks.Task<GraphResponse<EmptyEntityTypeWithBaseType>> UpdateResponseAsync(EmptyEntityTypeWithBaseType emptyEntityTypeWithBaseTypeToUpdate, CancellationToken cancellationToken = default(CancellationToken))
        {
            this.ContentType = CoreConstants.MimeTypeNames.Application.Json;
            this.Method = HttpMethods.PATCH;
            return this.SendAsyncWithGraphResponse<EmptyEntityTypeWithBaseType>(emptyEntityTypeWithBaseTypeToUpdate, cancellationToken);
        }

        /// <summary>
        /// Adds the specified expand value to the request.
        /// </summary>
        /// <param name="value">The expand value.</param>
        /// <returns>The request object to send.</returns>
        public IEmptyEntityTypeWithBaseTypeRequest Expand(string value)
        {
            this.QueryOptions.Add(new QueryOption("$expand", value));
            return this;
        }

        /// <summary>
        /// Adds the specified expand value to the request.
        /// </summary>
        /// <param name="expandExpression">The expression from which to calculate the expand value.</param>
        /// <returns>The request object to send.</returns>
        public IEmptyEntityTypeWithBaseTypeRequest Expand(Expression<Func<EmptyEntityTypeWithBaseType, object>> expandExpression)
        {
		    if (expandExpression == null)
            {
                throw new ArgumentNullException(nameof(expandExpression));
            }
            string error;
            string value = ExpressionExtractHelper.ExtractMembers(expandExpression, out error);
            if (value == null)
            {
                throw new ArgumentException(error, nameof(expandExpression));
            }
            else
            {
                this.QueryOptions.Add(new QueryOption("$expand", value));
            }
            return this;
        }

        /// <summary>
        /// Adds the specified select value to the request.
        /// </summary>
        /// <param name="value">The select value.</param>
        /// <returns>The request object to send.</returns>
        public IEmptyEntityTypeWithBaseTypeRequest Select(string value)
        {
            this.QueryOptions.Add(new QueryOption("$select", value));
            return this;
        }

        /// <summary>
        /// Adds the specified select value to the request.
        /// </summary>
        /// <param name="selectExpression">The expression from which to calculate the select value.</param>
        /// <returns>The request object to send.</returns>
        public IEmptyEntityTypeWithBaseTypeRequest Select(Expression<Func<EmptyEntityTypeWithBaseType, object>> selectExpression)
        {
            if (selectExpression == null)
            {
                throw new ArgumentNullException(nameof(selectExpression));
            }
            string error;
            string value = ExpressionExtractHelper.ExtractMembers(selectExpression, out error);
            if (value == null)
            {
                throw new ArgumentException(error, nameof(selectExpression));
            }
            else
            {
                this.QueryOptions.Add(new QueryOption("$select", value));
            }
            return this;
        }

        /// <summary>
        /// Initializes any collection properties after deserialization, like next requests for paging.
        /// </summary>
        /// <param name="emptyEntityTypeWithBaseTypeToInitialize">The <see cref="EmptyEntityTypeWithBaseType"/> with the collection properties to initialize.</param>
        private void InitializeCollectionProperties(EmptyEntityTypeWithBaseType emptyEntityTypeWithBaseTypeToInitialize)
        {

        }
    }
}
