// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: Templates\CSharp\Requests\IEntityRequestBuilder.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    /// <summary>
    /// The interface IEntityType3RequestBuilder.
    /// </summary>
    public partial interface IEntityType3RequestBuilder : IEntityRequestBuilder
    {
        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <returns>The built request.</returns>
        new IEntityType3Request Request();

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <param name="options">The query and header options for the request.</param>
        /// <returns>The built request.</returns>
        new IEntityType3Request Request(IEnumerable<Option> options);
    
        /// <summary>
        /// Gets the request builder for EntityType3Forward.
        /// </summary>
        /// <returns>The <see cref="IEntityType3ForwardRequestBuilder"/>.</returns>
        IEntityType3ForwardRequestBuilder Forward(
            IEnumerable<Recipient> ToRecipients,
            Recipient SingleRecipient,
            IEnumerable<Microsoft.Graph2.CallRecords.Session> MultipleSessions,
            Microsoft.Graph2.CallRecords.Session SingleSession,
            string Comment = null);
    
    }
}
