// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: IEntityCollectionPage.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Text.Json.Serialization;

    /// <summary>
    /// The interface ISecurityAlerts_v2CollectionPage.
    /// </summary>
    [InterfaceConverter(typeof(InterfaceConverter<SecurityAlerts_v2CollectionPage>))]
    public interface ISecurityAlerts_v2CollectionPage : ICollectionPage<Microsoft.Graph.SecurityNamespace.Alert>
    {
        /// <summary>
        /// Gets the next page <see cref="ISecurityAlerts_v2CollectionRequest"/> instance.
        /// </summary>
        ISecurityAlerts_v2CollectionRequest NextPageRequest { get; }

        /// <summary>
        /// Initializes the NextPageRequest property.
        /// </summary>
        void InitializeNextPageRequest(IBaseClient client, string nextPageLinkString);
    }
}
