// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: IEntityRequestBuilder.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    /// <summary>
    /// The interface IUserRequestBuilder.
    /// </summary>
    public partial interface IUserRequestBuilder : IDirectoryObjectRequestBuilder
    {
        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <returns>The built request.</returns>
        new IUserRequest Request();

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <param name="options">The query and header options for the request.</param>
        /// <returns>The built request.</returns>
        new IUserRequest Request(IEnumerable<Option> options);
    
        /// <summary>
        /// Gets the request builder for UserValidateProperties.
        /// </summary>
        /// <returns>The <see cref="IUserValidatePropertiesRequestBuilder"/>.</returns>
        IUserValidatePropertiesRequestBuilder ValidateProperties(
            string displayName = null,
            string mailNickname = null,
            Guid? onBehalfOfUserId = null);

        /// <summary>
        /// Gets the request builder for UserDelta.
        /// </summary>
        /// <returns>The <see cref="IUserDeltaRequestBuilder"/>.</returns>
        IUserDeltaRequestBuilder Delta();

        /// <summary>
        /// Gets the request builder for UserDelta.
        /// </summary>
        /// <returns>The <see cref="IUserDeltaRequestBuilder"/>.</returns>
        IUserDeltaRequestBuilder Delta(
            string token = null);
    
    }
}
