// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityType.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Text.Json.Serialization;

    /// <summary>
    /// The type Empty Entity Type With Base Type.
    /// </summary>
    [JsonConverter(typeof(DerivedTypeConverter<EmptyEntityTypeWithBaseType>))]
    public partial class EmptyEntityTypeWithBaseType : Entity
    {
    
		///<summary>
		/// The internal EmptyEntityTypeWithBaseType constructor
		///</summary>
        protected internal EmptyEntityTypeWithBaseType()
        {
            // Don't allow initialization of abstract entity types
        }
    
    }
}

