// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityType.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Text.Json.Serialization;

    /// <summary>
    /// The type Schedule.
    /// </summary>
    
    public partial class Schedule : Entity
    {
    
		///<summary>
		/// The Schedule constructor
		///</summary>
        public Schedule()
        {
            this.ODataType = "microsoft.graph.schedule";
        }
	
        /// <summary>
        /// Gets or sets enabled.
        /// </summary>
        [JsonPropertyName("enabled")]
        public bool? Enabled { get; set; }
    
        /// <summary>
        /// Gets or sets times off.
        /// </summary>
        [JsonPropertyName("timesOff")]
        public IScheduleTimesOffCollectionPage TimesOff { get; set; }
    
        /// <summary>
        /// Gets or sets time off requests.
        /// </summary>
        [JsonPropertyName("timeOffRequests")]
        public IScheduleTimeOffRequestsCollectionPage TimeOffRequests { get; set; }
    
    }
}

