// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: Templates\CSharp\Model\EntityType.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Text.Json.Serialization;

    /// <summary>
    /// The type Test Type.
    /// </summary>
    
    public partial class TestType : Entity
    {
    
		///<summary>
		/// The TestType constructor
		///</summary>
        public TestType()
        {
            this.ODataType = "microsoft.graph.testType";
        }
	
        /// <summary>
        /// Gets or sets property alpha.
        /// </summary>
        [JsonPropertyName("propertyAlpha")]
        [Obsolete("emptyBaseComplexTypeRequest is deprecated. Please use emptyBaseComplexTypeRequest2.")]
        public DerivedComplexTypeRequestObject PropertyAlpha { get; set; }
    
    }
}

