// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityCollectionWithReferencesPage.cs.tt

namespace Microsoft.Graph.ManagedTenants
{
    using System;

    /// <summary>
    /// The type ManagementTemplateCollectionManagementTemplatesCollectionWithReferencesPage.
    /// </summary>
    public partial class ManagementTemplateCollectionManagementTemplatesCollectionWithReferencesPage : Microsoft.Graph.CollectionPage<ManagementTemplate>, IManagementTemplateCollectionManagementTemplatesCollectionWithReferencesPage
    {
        /// <summary>
        /// Gets the next page <see cref="IManagementTemplateCollectionManagementTemplatesCollectionWithReferencesRequest"/> instance.
        /// </summary>
        public IManagementTemplateCollectionManagementTemplatesCollectionWithReferencesRequest NextPageRequest { get; private set; }

        /// <summary>
        /// Initializes the NextPageRequest property.
        /// </summary>
        public void InitializeNextPageRequest(Microsoft.Graph.IBaseClient client, string nextPageLinkString)
        {
            if (!string.IsNullOrEmpty(nextPageLinkString))
            {
                this.NextPageRequest = new ManagementTemplateCollectionManagementTemplatesCollectionWithReferencesRequest(
                    nextPageLinkString,
                    client,
                    null);
            }
        }
    }
}
