// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityRequestBuilder.cs.tt

namespace Microsoft.Graph2.CallRecords
{
    using System;
    using System.Collections.Generic;
    using System.IO;

    /// <summary>
    /// The type SingletonEntity1RequestBuilder.
    /// </summary>
    public partial class SingletonEntity1RequestBuilder : Microsoft.Graph.EntityRequestBuilder, ISingletonEntity1RequestBuilder
    {

        /// <summary>
        /// Constructs a new SingletonEntity1RequestBuilder.
        /// </summary>
        /// <param name="requestUrl">The URL for the built request.</param>
        /// <param name="client">The <see cref="Microsoft.Graph.IBaseClient"/> for handling requests.</param>
        public SingletonEntity1RequestBuilder(
            string requestUrl,
            Microsoft.Graph.IBaseClient client)
            : base(requestUrl, client)
        {
        }

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <returns>The built request.</returns>
        public new ISingletonEntity1Request Request()
        {
            return this.Request(null);
        }

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <param name="options">The query and header options for the request.</param>
        /// <returns>The built request.</returns>
        public new ISingletonEntity1Request Request(IEnumerable<Microsoft.Graph.Option> options)
        {
            return new SingletonEntity1Request(this.RequestUrl, this.Client, options);
        }
    
        /// <summary>
        /// Gets the request builder for TestSingleNav.
        /// </summary>
        /// <returns>The <see cref="Microsoft.Graph.ITestTypeRequestBuilder"/>.</returns>
        public Microsoft.Graph.ITestTypeRequestBuilder TestSingleNav
        {
            get
            {
                return new Microsoft.Graph.TestTypeRequestBuilder(this.AppendSegmentToRequestUrl("testSingleNav"), this.Client);
            }
        }
    
    }
}
