// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: ComplexType.cs.tt

namespace Microsoft.Graph2.CallRecords
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Runtime.Serialization;
    using Newtonsoft.Json;

    /// <summary>
    /// The type MediaStream.
    /// </summary>
    [JsonObject(MemberSerialization = MemberSerialization.OptIn)]
    [JsonConverter(typeof(Microsoft.Graph.DerivedTypeConverter))]
    public partial class MediaStream
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="MediaStream"/> class.
        /// </summary>
        public MediaStream()
        {
            this.ODataType = "microsoft.graph2.callRecords.mediaStream";
        }

        /// <summary>
        /// Gets or sets streamId.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "streamId", Required = Newtonsoft.Json.Required.Default)]
        public string StreamId { get; set; }
    
        /// <summary>
        /// Gets or sets startDateTime.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "startDateTime", Required = Newtonsoft.Json.Required.Default)]
        public DateTimeOffset? StartDateTime { get; set; }
    
        /// <summary>
        /// Gets or sets streamDirection.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "streamDirection", Required = Newtonsoft.Json.Required.Default)]
        public MediaStreamDirection? StreamDirection { get; set; }
    
        /// <summary>
        /// Gets or sets packetUtilization.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "packetUtilization", Required = Newtonsoft.Json.Required.Default)]
        public Int64? PacketUtilization { get; set; }
    
        /// <summary>
        /// Gets or sets wasMediaBypassed.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "wasMediaBypassed", Required = Newtonsoft.Json.Required.Default)]
        public bool? WasMediaBypassed { get; set; }
    
        /// <summary>
        /// Gets or sets lowVideoProcessingCapabilityRatio.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "lowVideoProcessingCapabilityRatio", Required = Newtonsoft.Json.Required.Default)]
        public Single? LowVideoProcessingCapabilityRatio { get; set; }
    
        /// <summary>
        /// Gets or sets averageAudioNetworkJitter.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "averageAudioNetworkJitter", Required = Newtonsoft.Json.Required.Default)]
        public Microsoft.Graph.Duration AverageAudioNetworkJitter { get; set; }
    
        /// <summary>
        /// Gets or sets additional data.
        /// </summary>
        [JsonExtensionData(ReadData = true)]
        public IDictionary<string, object> AdditionalData { get; set; }

        /// <summary>
        /// Gets or sets @odata.type.
        /// </summary>
        [JsonProperty(NullValueHandling = NullValueHandling.Ignore, PropertyName = "@odata.type", Required = Newtonsoft.Json.Required.Default)]
        public string ODataType { get; set; }
    
    }
}
