// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph2.callrecords.requests.extensions;
import com.microsoft.graph2.callrecords.requests.extensions.IPhotoRequest;
import com.microsoft.graph2.callrecords.requests.extensions.IPhotoStreamRequestBuilder;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The interface for the Photo Request Builder.
 */
public interface IPhotoRequestBuilder extends IRequestBuilder {
    /**
     * Creates the request
     *
     * @return the IPhotoRequest instance
     */
    IPhotoRequest buildRequest();

    /**
     * Creates the request with specific options instead of the existing options
     *
     * @param requestOptions the options for this request
     * @return the IPhotoRequest instance
     */
    IPhotoRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions);


    IPhotoStreamRequestBuilder content();

}
