// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph2.callrecords.requests.extensions;
import com.microsoft.graph2.callrecords.requests.extensions.ISegmentRequest;
import com.microsoft.graph2.callrecords.requests.extensions.SegmentRequest;
import com.microsoft.graph.requests.extensions.IEntityType3CollectionWithReferencesRequestBuilder;
import com.microsoft.graph.requests.extensions.EntityType3CollectionWithReferencesRequestBuilder;
import com.microsoft.graph.requests.extensions.IEntityType3WithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.EntityType3WithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.ICallWithReferenceRequestBuilder;
import com.microsoft.graph.requests.extensions.CallWithReferenceRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.ISessionWithReferenceRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.SessionWithReferenceRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.IPhotoRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.PhotoRequestBuilder;
import com.microsoft.graph.models.extensions.Recipient;
import com.microsoft.graph.models.extensions.Recipient;
import com.microsoft.graph2.callrecords.models.extensions.Session;
import com.microsoft.graph2.callrecords.models.extensions.Session;
import com.microsoft.graph2.callrecords.requests.extensions.ISegmentForwardRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.SegmentForwardRequestBuilder;
import com.microsoft.graph.models.extensions.IdentitySet;
import com.microsoft.graph2.callrecords.requests.extensions.ISegmentTestActionCollectionRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.SegmentTestActionCollectionRequestBuilder;

import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseRequestBuilder;
import com.microsoft.graph.options.Option;
import java.util.EnumSet;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Segment Request Builder.
 */
public class SegmentRequestBuilder extends BaseRequestBuilder implements ISegmentRequestBuilder {

    /**
     * The request builder for the Segment
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public SegmentRequestBuilder(final String requestUrl, final IBaseClient client, final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions);
    }

    /**
     * Creates the request
     *
     * @return the ISegmentRequest instance
     */
    public ISegmentRequest buildRequest() {
        return buildRequest(getOptions());
    }

    /**
     * Creates the request with specific requestOptions instead of the existing requestOptions
     *
     * @param requestOptions the options for this request
     * @return the ISegmentRequest instance
     */
    public ISegmentRequest buildRequest(final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        return new SegmentRequest(getRequestUrl(), getClient(), requestOptions);
    }


    public IEntityType3CollectionWithReferencesRequestBuilder refTypes() {
        return new EntityType3CollectionWithReferencesRequestBuilder(getRequestUrlWithAdditionalSegment("refTypes"), getClient(), null);
    }

    public IEntityType3WithReferenceRequestBuilder refTypes(final String id) {
        return new EntityType3WithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("refTypes") + "/" + id, getClient(), null);
    }

    /**
     * Gets the request builder for Call
     *
     * @return the ICallWithReferenceRequestBuilder instance
     */
    public ICallWithReferenceRequestBuilder refType() {
        return new CallWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("refType"), getClient(), null);
    }

    /**
     * Gets the request builder for Session
     *
     * @return the ISessionWithReferenceRequestBuilder instance
     */
    public ISessionWithReferenceRequestBuilder sessionRef() {
        return new SessionWithReferenceRequestBuilder(getRequestUrlWithAdditionalSegment("sessionRef"), getClient(), null);
    }

    /**
     * Gets the request builder for Photo
     *
     * @return the IPhotoRequestBuilder instance
     */
    public IPhotoRequestBuilder photo() {
        return new PhotoRequestBuilder(getRequestUrlWithAdditionalSegment("photo"), getClient(), null);
    }

    public ISegmentForwardRequestBuilder forward(final java.util.List<Recipient> toRecipients, final Recipient singleRecipient, final java.util.List<Session> multipleSessions, final Session singleSession, final String comment) {
        return new SegmentForwardRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph2.callRecords.forward"), getClient(), null, toRecipients, singleRecipient, multipleSessions, singleSession, comment);
    }

    public ISegmentTestActionCollectionRequestBuilder testAction(final IdentitySet value) {
        return new SegmentTestActionCollectionRequestBuilder(getRequestUrlWithAdditionalSegment("microsoft.graph2.callRecords.testAction"), getClient(), null, value);
    }
}

