// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph2.callrecords.requests.extensions;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.concurrency.ICallback;
import com.microsoft.graph.models.extensions.IdentitySet;
import com.microsoft.graph2.callrecords.models.extensions.Session;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph2.callrecords.requests.extensions.SegmentTestActionCollectionRequestBuilder;
import com.microsoft.graph2.callrecords.requests.extensions.SegmentTestActionCollectionPage;
import com.microsoft.graph2.callrecords.requests.extensions.SegmentTestActionCollectionResponse;
import com.microsoft.graph2.callrecords.models.extensions.SegmentTestActionBody;
import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.core.IBaseClient;
import com.microsoft.graph.http.BaseCollectionRequest;
import com.microsoft.graph.concurrency.IExecutors;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Segment Test Action Collection Request.
 */
public class SegmentTestActionCollectionRequest extends BaseCollectionRequest<SegmentTestActionCollectionResponse, SegmentTestActionCollectionPage> {


    protected final SegmentTestActionBody body;


    /**
     * The request for this SegmentTestAction
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public SegmentTestActionCollectionRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, SegmentTestActionCollectionResponse.class, SegmentTestActionCollectionPage.class);
        body = new SegmentTestActionBody();
    }


    public void post(@Nonnull final ICallback<? super SegmentTestActionCollectionPage> callback) {
        final IExecutors executors = getBaseRequest().getClient().getExecutors();
        executors.performOnBackground(new Runnable() {
           @Override
           public void run() {
                try {
                    executors.performOnForeground(post(), callback);
                } catch (final ClientException e) {
                    executors.performOnForeground(e, callback);
                }
           }
        });
    }

    @Nullable
    public SegmentTestActionCollectionPage post() throws ClientException {
        final SegmentTestActionCollectionResponse response = post(body);
        return buildFromResponse(response);
    }


    @Nonnull
    public SegmentTestActionCollectionPage buildFromResponse(@Nonnull final SegmentTestActionCollectionResponse response) {
        final SegmentTestActionCollectionRequestBuilder builder;
        if (response.nextLink != null) {
            builder = new SegmentTestActionCollectionRequestBuilder(response.nextLink, getBaseRequest().getClient(), /* options */ null, (IdentitySet) null);
        } else {
            builder = null;
        }
        final SegmentTestActionCollectionPage page = new SegmentTestActionCollectionPage(response, builder);
        page.setRawObject(response.getSerializer(), response.getRawObject());
        return page;
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    @Nonnull
    public SegmentTestActionCollectionRequest select(@Nonnull final String value) {
        addQueryOption(new com.microsoft.graph.options.QueryOption("$select", value));
        return (SegmentTestActionCollectionRequest)this;
    }

    /**
     * Sets the top value for the request
     *
     * @param value the max number of items to return
     * @return the updated request
     */
    @Nonnull
    public SegmentTestActionCollectionRequest top(final int value) {
        addQueryOption(new com.microsoft.graph.options.QueryOption("$top", value+""));
        return (SegmentTestActionCollectionRequest)this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    @Nonnull
    public SegmentTestActionCollectionRequest expand(@Nonnull final String value) {
        addQueryOption(new com.microsoft.graph.options.QueryOption("$expand", value));
        return (SegmentTestActionCollectionRequest)this;
    }

    /**
     * Sets the filter clause for the request
     *
     * @param value the filter clause
     * @return the updated request
     */
    @Nonnull
    public SegmentTestActionCollectionRequest filter(@Nonnull final String value) {
        addQueryOption(new com.microsoft.graph.options.QueryOption("$filter", value));
        return (SegmentTestActionCollectionRequest)this;
    }

    /**
     * Sets the order by clause for the request
     *
     * @param value the order by clause
     * @return the updated request
     */
    @Nonnull
    public SegmentTestActionCollectionRequest orderBy(@Nonnull final String value) {
        addQueryOption(new com.microsoft.graph.options.QueryOption("$orderby", value));
        return (SegmentTestActionCollectionRequest)this;
    }

}
