// Template Source: BaseEntityReferenceRequest.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.managedtenants.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.managedtenants.models.ManagementTemplate;
import com.microsoft.graph.managedtenants.requests.ManagementTemplateCollectionObjectCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.managedtenants.requests.ManagementTemplateCollectionObjectWithReferenceRequestBuilder;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.options.QueryOption;
import com.microsoft.graph.http.BaseReferenceRequest;
import com.microsoft.graph.http.HttpMethod;
import com.microsoft.graph.core.IBaseClient;
import com.google.gson.JsonPrimitive;
import com.google.gson.JsonObject;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Management Template Reference Request.
 */
public class ManagementTemplateReferenceRequest extends BaseReferenceRequest<ManagementTemplate> {

    /**
     * The request for the ManagementTemplate
     *
     * @param requestUrl     the request URL
     * @param client         the service client
     * @param requestOptions the options for this request
     */
    public ManagementTemplateReferenceRequest(@Nonnull final String requestUrl, @Nonnull final IBaseClient<?> client, @Nullable final java.util.List<? extends com.microsoft.graph.options.Option> requestOptions) {
        super(requestUrl, client, requestOptions, ManagementTemplate.class);
    }

    /**
     * Sets the select clause for the request
     *
     * @param value the select clause
     * @return the updated request
     */
    @Nonnull
    public ManagementTemplateReferenceRequest select(@Nonnull final String value) {
        addSelectOption(value);
        return this;
    }

    /**
     * Sets the expand clause for the request
     *
     * @param value the expand clause
     * @return the updated request
     */
    @Nonnull
    public ManagementTemplateReferenceRequest expand(@Nonnull final String value) {
        addExpandOption(value);
        return this;
    }
    /**
     * Puts the ManagementTemplate
     *
     * @param srcManagementTemplate the ManagementTemplate reference to PUT
     * @return a future with the result
     */
    @Nonnull
    public java.util.concurrent.CompletableFuture<ManagementTemplate> putAsync(@Nonnull final ManagementTemplate srcManagementTemplate) {
        final JsonObject payload = new JsonObject();
        payload.add("@odata.id", new JsonPrimitive(this.getClient().getServiceRoot() + "/managementTemplates/" + srcManagementTemplate.id));
        return sendAsync(HttpMethod.PUT, payload);
    }

    /**
     * Puts the ManagementTemplate
     *
     * @param srcManagementTemplate the ManagementTemplate reference to PUT
     * @return the ManagementTemplate
     * @throws ClientException an exception occurs if there was an error while the request was sent
     */
    @Nullable
    public ManagementTemplate put(@Nonnull final ManagementTemplate srcManagementTemplate) throws ClientException {
        final JsonObject payload = new JsonObject();
        payload.add("@odata.id", new JsonPrimitive(this.getClient().getServiceRoot() + "/managementTemplates/" + srcManagementTemplate.id));
        return send(HttpMethod.PUT, payload);
    }
}
