// Template Source: BaseEntityCollectionWithReferencesPage.java.tt
// ------------------------------------------------------------------------------
// Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

package com.microsoft.graph.managedtenants.requests;

import com.microsoft.graph.http.IRequestBuilder;
import com.microsoft.graph.core.ClientException;
import com.microsoft.graph.managedtenants.models.ManagementTemplate;
import com.microsoft.graph.managedtenants.models.ManagementTemplateCollectionObject;
import java.util.Arrays;
import java.util.EnumSet;
import javax.annotation.Nullable;
import javax.annotation.Nonnull;

import com.microsoft.graph.managedtenants.requests.ManagementTemplateCollectionObjectCollectionWithReferencesRequestBuilder;
import com.microsoft.graph.managedtenants.requests.ManagementTemplateCollectionObjectCollectionWithReferencesPage;
import com.microsoft.graph.managedtenants.requests.ManagementTemplateCollectionObjectCollectionResponse;
import com.microsoft.graph.managedtenants.models.ManagementTemplateCollectionObject;
import com.google.gson.JsonObject;
import com.google.gson.annotations.SerializedName;
import com.google.gson.annotations.Expose;
import com.microsoft.graph.http.BaseCollectionPage;

// **NOTE** This file was generated by a tool and any changes will be overwritten.

/**
 * The class for the Management Template Collection Object Collection With References Page.
 */
public class ManagementTemplateCollectionObjectCollectionWithReferencesPage extends BaseCollectionPage<ManagementTemplateCollectionObject, ManagementTemplateCollectionObjectCollectionWithReferencesRequestBuilder> {

    /**
     * A collection page for ManagementTemplateCollectionObject
     *
     * @param response the serialized ManagementTemplateCollectionObjectCollectionResponse from the service
     * @param builder  the request builder for the next collection page
     */
    public ManagementTemplateCollectionObjectCollectionWithReferencesPage(@Nonnull final ManagementTemplateCollectionObjectCollectionResponse response, @Nullable final ManagementTemplateCollectionObjectCollectionWithReferencesRequestBuilder builder) {
        super(response.value, builder, response.additionalDataManager());
    }

    /**
     * Creates the collection page for ManagementTemplateCollectionObject
     *
     * @param pageContents       the contents of this page
     * @param nextRequestBuilder the request builder for the next page
     */
    public ManagementTemplateCollectionObjectCollectionWithReferencesPage(@Nonnull final java.util.List<ManagementTemplateCollectionObject> pageContents, @Nullable final ManagementTemplateCollectionObjectCollectionWithReferencesRequestBuilder nextRequestBuilder) {
        super(pageContents, nextRequestBuilder);
    }
}
